# Generated by Django 4.2.4 on 2025-03-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroups',
            name='is_making_sale',
            field=models.BooleanField(default=True),
        ),
    ]
