# Generated by Django 4.2.4 on 2025-03-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroups', '0002_productgroups_is_making_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroups',
            name='group_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productgroups',
            name='is_making_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
