# Generated by Django 4.2.4 on 2025-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroups', '0003_alter_productgroups_group_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroups',
            name='group_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
