# Generated by Django 4.2.4 on 2025-03-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroups', '0004_alter_productgroups_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroups',
            name='note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
