# Generated by Django 4.2.4 on 2025-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroups', '0005_alter_productgroups_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroups',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
