# Generated by Django 4.2.4 on 2025-03-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField()),
                ('order_fullname', models.CharField(max_length=255)),
                ('order_phone', models.CharField(max_length=20)),
                ('order_address', models.TextField()),
                ('order_qty_amt', models.IntegerField()),
                ('order_note', models.TextField(blank=True, null=True)),
                ('order_url', models.CharField(blank=True, max_length=500, null=True)),
                ('order_status', models.CharField(max_length=50)),
                ('ads_utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_adsid', models.CharField(blank=True, max_length=255, null=True)),
                ('order_confirmation', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG'), ('KNM', 'KNM')], max_length=10)),
                ('order_id_index', models.CharField(max_length=255)),
                ('updated_user', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('user_update', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.landingorder')),
            ],
        ),
    ]
