# Generated by Django 4.2.4 on 2025-03-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingorder',
            old_name='order_id_index',
            new_name='order_id',
        ),
    ]
