# Generated by Django 4.2.4 on 2025-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_id_index_landingorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingorder',
            name='order_qty_amt',
            field=models.TextField(),
        ),
    ]
