# Generated by Django 4.2.4 on 2025-03-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_landingorder_order_qty_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_user', models.CharField(max_length=255)),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.landingorder')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderLog',
        ),
    ]
