# Generated by Django 4.2.4 on 2025-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_landingorder_id_alter_orderupdatelog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderupdatelog',
            name='order',
        ),
        migrations.AddField(
            model_name='orderupdatelog',
            name='order_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingorder',
            name='order_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='landingorder',
            name='order_qty_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='landingorder',
            name='order_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderupdatelog',
            name='field_changed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderupdatelog',
            name='new_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderupdatelog',
            name='old_value',
            field=models.TextField(null=True),
        ),
    ]
