# Generated by Django 4.2.4 on 2025-03-21 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_remove_landingorder_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField()),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('order_fullname', models.CharField(max_length=100)),
                ('order_phone', models.CharField(max_length=20)),
                ('order_address', models.TextField()),
                ('order_qty_amt', models.TextField()),
                ('order_note', models.TextField(blank=True, null=True)),
                ('order_url', models.URLField()),
                ('order_status', models.CharField(max_length=50)),
                ('ads_utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('ads_utm_content', models.CharField(blank=True, max_length=100, null=True)),
                ('ads_utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('ads_utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('ads_adsid', models.CharField(blank=True, max_length=100, null=True)),
                ('order_confirmation', models.CharField(blank=True, choices=[('', 'Blank'), ('OK', 'OK'), ('NG', 'NG'), ('KNM', 'KNM')], default='', max_length=4)),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LandingOrder',
        ),
        migrations.DeleteModel(
            name='OrderUpdateLog',
        ),
    ]
