# Generated by Django 4.2.4 on 2025-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_orderlog_delete_landingorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_confirmation',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('KNM', 'KNM')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='updated_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
