# Generated by Django 4.2.4 on 2025-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_qty_amt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
