# Generated by Django 4.2.4 on 2025-03-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_order_id_order_assign_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
