# Generated by Django 4.2.4 on 2025-03-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
