# Generated by Django 4.2.4 on 2025-03-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_order_status_order_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
