# Generated by Django 4.2.4 on 2025-04-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderlog',
            table='order_logs',
        ),
    ]
