# Generated by Django 4.2.4 on 2025-04-01 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cod_orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('cod_date', models.DateTimeField()),
                ('cod_code', models.CharField(default='', max_length=20)),
                ('cod_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(max_length=50)),
                ('price_number', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('cost_product', models.CharField(default='', max_length=50)),
                ('cost_product_qty', models.IntegerField()),
                ('cod_get_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_transfer_date', models.DateField()),
                ('cod_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cod_orders',
            },
        ),
    ]
