# Generated by Django 4.2.4 on 2025-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cod_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod_orders',
            name='cod_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cod_orders',
            name='cod_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cod_orders',
            name='cod_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cod_orders',
            name='cod_transfer_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='cod_orders',
            name='cost_product_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cod_orders',
            name='price_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cod_orders',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
