# Generated by Django 4.2.4 on 2025-03-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('bill_name', models.CharField(max_length=255)),
                ('product_unit', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PrdUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_url', models.URLField(max_length=500)),
                ('url_number', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='products.product')),
            ],
            options={
                'db_table': 'products_urls',
                'unique_together': {('product', 'url_number')},
            },
        ),
        migrations.CreateModel(
            name='PrdPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_number', models.IntegerField()),
                ('price_name', models.CharField(max_length=100)),
                ('prd_quantity', models.IntegerField()),
                ('prd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('landing_qty_amt', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'db_table': 'products_prices',
                'unique_together': {('product', 'price_number')},
            },
        ),
    ]
