# Generated by Django 4.2.4 on 2025-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
