# Generated by Django 4.2.4 on 2025-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdprice',
            name='cost_product',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prdprice',
            name='cost_product_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
