# Generated by Django 4.2.4 on 2025-03-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prdprice_cost_product_prdprice_cost_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdprice',
            name='cost_product',
            field=models.CharField(max_length=50),
        ),
    ]
