# Generated by Django 4.2.4 on 2025-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_prdprice_cost_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdurl',
            name='url_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prdprice',
            name='cost_product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
