# Generated by Django 4.2.4 on 2025-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_prdurl_url_name_alter_prdprice_cost_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdprice',
            name='cost_product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
