# Generated by Django 4.2.4 on 2025-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_prdprice_cost_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
